meta_product_name: "Le Baroudeur"
meta_title: "Le Baroudeur - Des produits originaux"
meta_description: "Des idées de gagdets, de livres, de fringues et bien plus."
meta_image: "oumanger.jpg" # should exist in `app/assets/images/`
twitter_account: ""   # required for Twitter Cards
